# Community Phylogenetics {#comm_phylo}

**How do species’ evolutionary relationships explain responses?**

## Basic plotting

```{r}
par(mfrow=c(1,3), mar=c(0,0,0,0), oma=c(0,0,0,0))           # plotting parameters
plot(phy, cex=0.75, no.margin=T)                            # basic plotting
plot(phy, cex=0.75, tip.color=colvec(tra$lfp), no.margin=T) # color labels by traits
plot(phy, cex=0.75, label.offset=48, no.margin=T)           # symbolize trait values at tips
tiplabels(pch=21, bg = c(tra$annual),    adj=0)
tiplabels(pch=21, bg = c(tra$biennial),  adj=15)
tiplabels(pch=21, bg = c(tra$perennial), adj=30)
```


## Phylogenetic diversity - alpha

According to some people, phylogenetic diversity lets you infer community assembly processes (competitive exclusion, environmental filtering, neutral dynamics). Some other serious people doubt this.

```{r}
### phylogenetic distance matrix
Dp  <- cophenetic(phy) 

### Faith's phylogenetic diversity:
###  total branch length connecting
###   all species per site
fpd <- pd(spe, phy)

### mean pairwise distance
mpd <- ses.mpd(
  spe, Dp, null.model='independentswap')

### mean nearest taxon distance
mnd <- ses.mntd(
  spe, Dp, null.model='independentswap')

### bring all together
phy_div <- 
  cbind(fpd, 
        mpd  = mpd$mpd.obs.z, 
        mntd = mnd$mntd.obs.z)

phy_div
```

